# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
# GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
# Go modules in dev branch
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  ## group dependencies with following prefixes into a single PR.
  groups:
    all-dependencies:
      patterns: [ "*" ]
  target-branch: "dev"
