# Reverse Proxy Server URL
serverURL: http://127.0.0.1:8080
# Bind Address
bindAddr: 127.0.0.1
listen: 8080

# TLS Certificate
certFile: ""
keyFile: ""

# Enable the redirect blobs to CDN cached URL
redirectBlobsLocation:
  enabled: true
  url: https://cdn-blobs.example.com
  authConfig:
    # CDN auth token
    # https://cloud.tencent.com/document/product/228/41625
    tokenEnvKey: BLOBS_CDN_AUTH_TOKEN # Env Key for Auth Token

# Remote registry server
remoteURL: http://registry.example.com
insecureSkipTLSVerify: false
repositories:
  - name: library
    private: false
  - name: test1
    private: true
  - name: test2
    private: true

# Other custom routes
customRoutes:
  - prefix: /text
    plainText:
      content: |
        This is a plain text response
      status: 200
  - prefix: /favicon.ico
    plainText:
      content: |
        404 not found
      status: 404
