# Reverse Proxy Server URL
serverURL: http://127.0.0.1:8080
# Bind Address
bindAddr: 127.0.0.1
listen: 8080

# TLS Certificate
certFile: ""
keyFile: ""

# Remote registry server
remoteURL: http://registry.example.com
insecureSkipTLSVerify: false
repositories:
  - name: library
    private: false
  - name: test1
    private: true
  - name: test2
    private: true

# Other custom routes
customRoutes:
  - prefix: /text
    plainText:
      content: |
          This is a plain text response
      status: 200
  - prefix: /favicon.ico
    plainText:
      content: |
          404 not found
      status: 404
