name: "Create GitHub Release"
description: "Create GitHub Release"
runs:
  using: "composite"
  steps:
    - name: Create release notes
      shell: bash
      run: |
        set -x
        # Ensure GitHub Release Exists
        EXPECTED_TITLE="${{ github.ref_name }}"
        EXTRA_OPTIONS=""
        if [[ $EXPECTED_TITLE = *rc* ]] || [[ $EXPECTED_TITLE = *beta* ]] || [[ $EXPECTED_TITLE = *alpha* ]]; then
          EXPECTED_TITLE="Pre-release $EXPECTED_TITLE"
          EXTRA_OPTIONS="${EXTRA_OPTIONS} --prerelease"
        fi
        EXISTS=$(gh release list -R ${{ github.repository }} --json name --jq ".[] | select(.name == \"${EXPECTED_TITLE}\")")
        if [[ "$EXISTS" == "" ]]; then
          gh release create "${{ github.ref_name }}" -R ${{ github.repository }} --title "$EXPECTED_TITLE" --generate-notes $EXTRA_OPTIONS
        fi
