name: Push CI

on:
  pull_request:
  push:
    branches: [ '**' ]
    tags-ignore: [ '**' ] # Disable Tag

env:
  REGISTRY: "localhost:5000"
  REPOSITORY: "library"

jobs:
  ci:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Lint
        uses: golangci/golangci-lint-action@v8
      - name: Test
        run: |
          make test
  image-build:
    runs-on: 'ubuntu-latest'
    services:
      registry:
        image: registry.suse.com/suse/registry:2.8
        ports:
          - 5000:5000
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
      - name: Image Build
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            TAG=${{ github.ref_name }}
            COMMIT=${{ github.sha }}
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/overlayer:dev
          platforms: "linux/amd64"
          file: package/Dockerfile
          sbom: true
          provenance: mode=max
